kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shenhengheng-rt-pv-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
