apiVersion: v1
kind: Service
metadata:
  labels:
    app: rt
  name: shenhengheng-rt
  namespace: default
spec:
  clusterIP: 10.99.86.211
  externalIPs:
  - 172.16.3.19
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30844
    port: 38888
    protocol: TCP
    targetPort: 8888
  selector:
    app: rt
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
